### ISSUE TITLE
Does not work anymore in VSCode Version 1.25.0 (1.25.0)

### ISSUE THREAD

**Issue by vitodcampanelli** [tschf/odb-task#13]
Seems to compile about sqlplus although all setting are correct
![screen shot 2018-07-10 at 8 37 40 am](https://user-images.githubusercontent.com/12102777/42510381-b5f04192-841c-11e8-9465-791b4551a429.png)

**Comment by tschf** [comment]
I just upgraded and compiled and did not get this warning. I've seen this error in the past when try running the command and the config isn't properly set up. Fixing and then reloading VSC and the error goes away. Any repro steps? You still get it after reloading code?

**Comment by vitodcampanelli** [comment]
All good, totally my fault. I did not drill down to the project itself, I was in the parent folder. Sorry.
