### ISSUE TITLE
Add support for key bindings

### ISSUE THREAD

**Issue by tschf** [tschf/odb-task#3]

**Comment by vitodcampanelli** [comment]
You can configure it using one of these methods:

-1
Click on Prefenences
Click on Keyboard Shortcuts
Search for Compile with Sqlcl or Compile with SqlPlus
Right click select Add Keybinding
Define your keybinding

-2 
Simply add it in the user keybindings.json file

**Comment by vincentmorneau** [comment]
@vitodcampanelli Your solution works. Why keep this issue opened? This is how every keybinding works in VSC.

**Comment by tschf** [comment]
Yes - fair point. Once I update the documentation, I'll close this.
