### ISSUE TITLE
SP2-0310: Unable to open file: "&1.sql"

### ISSUE THREAD

**Issue by vitodcampanelli** [tschf/odb-task#8]
Getting the following error when compiling package spec.

`Compiling script: &1

Error starting at line : 19 File @ /Users/vitoc/.vscode/extensions/tschf.odb-task-0.0.2/dist/compile.sql
In command -
@"&1"
Error report -
SP2-0310: Unable to open file: "&1.sql"
No errors.`

**Comment by tschf** [comment]
@vitodcampanelli Thanks for testing and the report. This is odd, it looks like it's not picking up your active file. You are working with a saved file, right? What version are you on? Not sure what other info will help me reproduce 🤔 
 
FWIW, I've tested the extension on Windows and Linux systems without issue. I can add a warning when it doesn't pick up the saved file, but this won't resolve the underlying issue you faced.

**Comment by vitodcampanelli** [comment]
@tschf Yes I am working with a saved file. I am on a Mac, with sqlcl defined in my path, so can be executed from anywhere.
SQLcl: Release 17.3.0.256.1818 Production
Code: Version 1.19.1 (1.19.1)

**Comment by vitodcampanelli** [comment]
@tschf I managed to get it to work by adding `set define on` to the script compile.sql.
I am not sure if it is worth while to add to add it to your file.
