### ISSUE TITLE
Ability to save the file when you compile it.

### ISSUE THREAD

**Issue by vitodcampanelli** [tschf/odb-task#9]
When you edit a package, you need to save before you recompile.
It would be nice if when you try to compile, it does a save and then compiles.

**Comment by tschf** [comment]
Added an auto save preference which defaults to false. On next publish you can enable this flag to have it save before compilation. Added a warning message if this is toggled off and the file is not saved when compiling.

![image](https://user-images.githubusercontent.com/1747643/46233926-8ddb0880-c342-11e8-9d0c-1bc6b05063a1.png)
